export default interface MessageTypes {
  TEXT: string;
  AUDIO: string;
  VOICE: string;
  IMAGE: string;
  VIDEO: string;
  DOCUMENT: string;
  STICKER: string;
  LOCATION: string;
  CONTACT_CARD: string;
  CONTACT_CARD_MULTI: string;
  ORDER: string;
  REVOKED: string;
  PRODUCT: string;
  UNKNOWN: string;
  GROUP_INVITE: string;
  LIST: string;
  LIST_RESPONSE: string;
  BUTTONS_RESPONSE: string;
  PAYMENT: string;
  BROADCAST_NOTIFICATION: string;
  CALL_LOG: string;
  CIPHERTEXT: string;
  DEBUG: string;
  E2E_NOTIFICATION: string;
  GP2: string;
  GROUP_NOTIFICATION: string;
  HSM: string;
  INTERACTIVE: string;
  NATIVE_FLOW: string;
  NOTIFICATION: string;
  NOTIFICATION_TEMPLATE: string;
  OVERSIZED: string;
  PROTOCOL: string;
  REACTION: string;
  TEMPLATE_BUTTON_REPLY;
}
