on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:
  
jobs:
  buid:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2 
      
      - run: npm --prefix /home/admin/mordomo-lata run start
